### ISSUE TITLE
--headless always picking a candidate can cause builds to fail

### ISSUE THREAD

**Issue by aw94** [KSP-CKAN/CKAN-core#88]
Case in point: https://github.com/KSP-CKAN/NetKAN/pull/900

Last build failed because a Custom Asteroids config was picked even though a Custom Asteroids config was being tested...

**Comment by aw94** [comment]
Seems to be only if what's in "provides" isn't also put into "conflicts"?

**Comment by Dazpoet** [comment]
I would agree that the conflicts missing probably made things a little screwy. Also that PR required overhauling of RSS netkan file which might have been doing something with customasteroids from the start considering it tends to install all of RO, its dependencies and recommendations aswell as half of the mod repository as an effect of RO being RO.

Jenkins failing builds due to installing mods already in CKAN-meta which conflic with the tested mods is something of an edgecase which I'm also running into with https://github.com/KSP-CKAN/NetKAN/pull/889.

I'll close this because the initial problem proved not to be a problem and Jenkins edgecases should be its own discussion if it ever proves to be more than an annoyance when mucking about with complex metadata.
